pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = "NeoForged"
			url = uri("https://maven.neoforged.net/releases")
			content {
				includeGroup("net.neoforged")
			}
		}
		mavenCentral()
	}

	plugins {
		id 'net.neoforged.moddev' version '2.0.148'
		id 'net.neoforged.moddev.repositories' version '2.0.148'
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
	id 'net.neoforged.moddev.repositories'
}

dependencyResolutionManagement {
	repositoriesMode = RepositoriesMode.PREFER_SETTINGS

	repositories {
		maven {
			name = "NeoForged"
			url = uri("https://maven.neoforged.net/releases")
			content {
				includeGroup("net.neoforged")
			}
		}
		maven {
			name = "ParchmentMC"
			url = uri("https://maven.parchmentmc.org")
			content {
				includeGroup("org.parchmentmc.data")
			}
		}
		mavenCentral()
	}
}

rootProject.name = 'CreateArrowsIncluded'
