package dev.mackery.arrowsincluded;

import org.lwjgl.glfw.GLFW;
import org.slf4j.Logger;

import com.mojang.logging.LogUtils;

import dev.mackery.arrowsincluded.mixin.MouseHandlerInvoker;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;

/**
 * Turns arrow key presses into mouse wheel scrolls while Alt (or a mouse button) is held.
 * <p>
 * Some laptop touchpads and desktops swallow two-finger scrolling while Alt is held, so Create's
 * ALT menus (schematic tools, toolbox, ...) can't be scrolled. The scroll is injected through
 * vanilla's own {@code MouseHandler#onScroll}, so every mod that reacts to scrolling, via events
 * or mixins, sees it exactly like a real wheel tick.
 */
public final class ArrowScroll {

	private static final Logger LOGGER = LogUtils.getLogger();

	private static final String CREATE_WRENCH_MENU = "com.simibubi.create.content.contraptions.wrench.RadialWrenchMenu";

	private static boolean synthetic;

	private ArrowScroll() {}

	/** True while a scroll generated by this mod is being dispatched. */
	public static boolean isSynthetic() {
		return synthetic;
	}

	/**
	 * Called at the start of every key event. Returns true when the key was turned into a scroll
	 * and should not be processed any further.
	 */
	public static boolean onKey(long windowPointer, int key, int action, int modifiers) {
		int direction = scrollDirection(key);
		if (direction == 0 || action == GLFW.GLFW_RELEASE)
			return false;

		Minecraft mc = Minecraft.getInstance();
		if (windowPointer != mc.getWindow().getWindow())
			return false;

		Screen screen = mc.screen;
		boolean altHeld = (modifiers & GLFW.GLFW_MOD_ALT) != 0 || Screen.hasAltDown();
		boolean mouseHeld = isMouseButtonHeld(windowPointer);
		boolean wrenchMenu = screen != null && screen.getClass().getName().equals(CREATE_WRENCH_MENU);
		LOGGER.debug("Arrow key {} (action {}, modifiers {}): alt={}, mouse={}, screen={}", key, action, modifiers, altHeld, mouseHeld,
			screen == null ? "none" : screen.getClass().getName());

		if (screen != null && screen.getFocused() instanceof EditBox)
			return false;
		// Create's wrench menu is held open by its own (rebindable) key, so it doesn't need Alt
		if (!altHeld && !mouseHeld && !wrenchMenu)
			return false;

		scroll(direction);
		return true;
	}

	/**
	 * Up/Left scroll up, Down/Right scroll down, which matches the direction Create's
	 * horizontal tool bar moves when scrolling.
	 */
	private static int scrollDirection(int key) {
		return switch (key) {
			case GLFW.GLFW_KEY_UP, GLFW.GLFW_KEY_LEFT -> 1;
			case GLFW.GLFW_KEY_DOWN, GLFW.GLFW_KEY_RIGHT -> -1;
			default -> 0;
		};
	}

	/** A held mouse button covers "click and scroll" controls, e.g. Simulated's physics staff and handles. */
	private static boolean isMouseButtonHeld(long window) {
		return GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_LEFT) == GLFW.GLFW_PRESS
			|| GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_RIGHT) == GLFW.GLFW_PRESS
			|| GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_MIDDLE) == GLFW.GLFW_PRESS;
	}

	private static void scroll(int direction) {
		Minecraft mc = Minecraft.getInstance();
		double amount = direction;
		// onScroll multiplies by the wheel sensitivity option, which trackpad users often lower;
		// undo that so one key press is always one full wheel tick
		double sensitivity = mc.options.mouseWheelSensitivity().get();
		if (!mc.options.discreteMouseScroll().get() && sensitivity > 0)
			amount /= sensitivity;

		synthetic = true;
		try {
			((MouseHandlerInvoker) mc.mouseHandler).arrowsincluded$onScroll(mc.getWindow().getWindow(), 0, amount);
		} finally {
			synthetic = false;
		}
	}
}
