package dev.mackery.arrowsincluded;

import org.lwjgl.glfw.GLFW;

import dev.mackery.arrowsincluded.mixin.MouseHandlerInvoker;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.InputEvent;
import net.neoforged.neoforge.client.event.ScreenEvent;

/**
 * Turns arrow key presses into mouse wheel scrolls while Alt (or a mouse button) is held.
 * <p>
 * Some laptop touchpads and desktops swallow two-finger scrolling while Alt is held, so Create's
 * ALT menus (schematic tools, toolbox, ...) can't be scrolled. The scroll is injected through
 * vanilla's own {@code MouseHandler#onScroll}, so every mod that reacts to scrolling, via events
 * or mixins, sees it exactly like a real wheel tick.
 */
@EventBusSubscriber(modid = ArrowsIncluded.MOD_ID, value = Dist.CLIENT)
public final class ArrowScroll {

	private static final String CREATE_WRENCH_MENU = "com.simibubi.create.content.contraptions.wrench.RadialWrenchMenu";

	private static boolean synthetic;

	private ArrowScroll() {}

	/** True while a scroll generated by this mod is being dispatched. */
	public static boolean isSynthetic() {
		return synthetic;
	}

	@SubscribeEvent
	public static void onKey(InputEvent.Key event) {
		// Screens are handled in onScreenKey, before the screen uses the arrows for widget navigation
		if (Minecraft.getInstance().screen != null || event.getAction() == GLFW.GLFW_RELEASE)
			return;
		int direction = scrollDirection(event.getKey());
		if (direction != 0 && isTriggerHeld())
			scroll(direction);
	}

	@SubscribeEvent
	public static void onScreenKey(ScreenEvent.KeyPressed.Pre event) {
		int direction = scrollDirection(event.getKeyCode());
		if (direction == 0)
			return;
		Screen screen = event.getScreen();
		if (screen.getFocused() instanceof EditBox)
			return;
		// Create's wrench menu is held open by its own (rebindable) key, so it doesn't need Alt
		if (!isTriggerHeld() && !screen.getClass().getName().equals(CREATE_WRENCH_MENU))
			return;
		scroll(direction);
		event.setCanceled(true);
	}

	/**
	 * Up/Left scroll up, Down/Right scroll down, which matches the direction Create's
	 * horizontal tool bar moves when scrolling.
	 */
	private static int scrollDirection(int key) {
		return switch (key) {
			case GLFW.GLFW_KEY_UP, GLFW.GLFW_KEY_LEFT -> 1;
			case GLFW.GLFW_KEY_DOWN, GLFW.GLFW_KEY_RIGHT -> -1;
			default -> 0;
		};
	}

	private static boolean isTriggerHeld() {
		long window = Minecraft.getInstance().getWindow().getWindow();
		// A held mouse button covers "click and scroll" controls, e.g. Simulated's physics staff and handles
		return Screen.hasAltDown()
			|| GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_LEFT) == GLFW.GLFW_PRESS
			|| GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_RIGHT) == GLFW.GLFW_PRESS
			|| GLFW.glfwGetMouseButton(window, GLFW.GLFW_MOUSE_BUTTON_MIDDLE) == GLFW.GLFW_PRESS;
	}

	private static void scroll(int direction) {
		Minecraft mc = Minecraft.getInstance();
		double amount = direction;
		// onScroll multiplies by the wheel sensitivity option, which trackpad users often lower;
		// undo that so one key press is always one full wheel tick
		double sensitivity = mc.options.mouseWheelSensitivity().get();
		if (!mc.options.discreteMouseScroll().get() && sensitivity > 0)
			amount /= sensitivity;

		synthetic = true;
		try {
			((MouseHandlerInvoker) mc.mouseHandler).arrowsincluded$onScroll(mc.getWindow().getWindow(), 0, amount);
		} finally {
			synthetic = false;
		}
	}
}
